import pytest
import json
from pathlib import Path
from backend.models.query import AnalysisRequest
from backend.models.analysis import AnalysisStatus
from backend.api.dependencies import get_orchestrator
from backend.data.catalog import dataset_catalog

@pytest.fixture(scope="module")
def kaggle_datasets():
    return [d["dataset_id"] for d in dataset_catalog.list_datasets()]

def test_kaggle_dataset_manifest_exists():
    manifest_path = Path("data/dataset_manifest.json")
    assert manifest_path.exists(), "data/dataset_manifest.json should exist."
    with open(manifest_path, "r") as f:
        data = json.load(f)
    assert "datasets" in data
    assert "orders" in data["datasets"]
    assert "customers" in data["datasets"]
    assert len(data["relationships"]) > 0

def test_kaggle_total_revenue(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="What is the total revenue?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert res.canonical_result.result > 2.0e9  # Ground truth ~ 2.57B INR

def test_kaggle_average_order_value(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="What is the average order value?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert abs(res.canonical_result.result - 25725.92) < 100.0

def test_kaggle_category_revenue(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="Which product category generated the highest revenue?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert res.canonical_result.metric == "Electronics"

def test_kaggle_premium_customer_revenue(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="What is the total revenue generated by Premium customers?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert res.canonical_result.result > 8.0e8  # Ground truth ~ 8.83E8 INR

def test_kaggle_highest_sales_state(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="Which state generated the highest sales?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert res.canonical_result.metric == "Maharashtra"

def test_kaggle_return_rate(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="What percentage of orders were returned?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert abs(res.canonical_result.result - 9.51) < 1.0

def test_kaggle_highest_aov_segment(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="Which customer segment has the highest average order value?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert res.canonical_result.metric == "Premium"

def test_kaggle_returning_customers_revenue(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="What is the revenue generated by customers who returned products?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert res.canonical_result.result > 1.0e9

def test_kaggle_highest_return_category(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="Which product category has the highest return rate?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert res.canonical_result is not None
    assert res.canonical_result.metric == "Footwear"

def test_kaggle_missing_profit_refusal(kaggle_datasets):
    orchestrator = get_orchestrator()
    # Query requesting profit from orders table (which lacks net profit column)
    orders_only = [d for d in kaggle_datasets if "orders" in d and "items" not in d]
    req = AnalysisRequest(
        question="What is the net profit for Q3?",
        selected_datasets=orders_only
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.REFUSED
    assert res.refusal_reason == "insufficient_data"

def test_kaggle_return_prediction_ml(kaggle_datasets):
    orchestrator = get_orchestrator()
    req = AnalysisRequest(
        question="Which orders are most likely to be returned?",
        selected_datasets=kaggle_datasets
    )
    res = orchestrator.process_analysis(req)
    assert res.status == AnalysisStatus.VERIFIED
    assert "[MODEL PREDICTION]" in res.answer
    assert "CatBoostClassifier" in res.answer
